# Generated by Django 4.0.6 on 2022-07-30 08:15

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('birthday', models.DateField()),
                ('rank', models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Bwn', 'Brown'), ('Blk', 'Black')], default='W', max_length=5)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('UP', 'Upcoming: Less than 18'), ('P', 'Prime: Less than 40'), ('MID', 'Middle: 40 to Less than 55'), ('MSTR', 'Masters: 55 or More')], default='UP', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('date_of_tournament', models.DateTimeField()),
                ('address', models.CharField(default='Address', max_length=100)),
                ('city', models.CharField(default='City', max_length=100)),
                ('state_or_province', models.CharField(default='State or Province', max_length=100)),
                ('nation', models.CharField(default='Nation', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Bwn', 'Brown'), ('Blk', 'Black')], default='W', max_length=5)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.age')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(choices=[('125', 'Less than 125'), ('135', '125 to Less than 135'), ('145', '135 to Less than 145'), ('155', '145 to Less than 155'), ('165', '155 to Less than 165'), ('175', '165 to Less than 175'), ('185', '175 to Less than 185'), ('195', '185 to Less than 195'), ('205', '195 to Less than 205'), ('215', '205 to Less than 215'), ('225', '215 to Less than 225'), ('235', '225 to Less than 235'), ('245', '235 to Less than 245'), ('H', '145 or More')], default='125', max_length=4)),
                ('number_of_competitors', models.IntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tournament Name', max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
            options={
                'verbose_name_plural': 'Sexes',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.weight')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True)),
                ('competitorA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitorA', to='accounts.competitor')),
                ('competitorB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompetitorB', to='accounts.competitor')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.round')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='accounts.competitor')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.tournament'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.weight'),
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2)),
                ('age', models.CharField(choices=[('UP', 'Upcoming: Less than 18'), ('P', 'Prime: Less than 40'), ('MID', 'Middle: 40 to Less than 55'), ('MSTR', 'Masters: 55 or More')], default='UP', max_length=5)),
                ('rank', models.CharField(choices=[('W', 'White'), ('B', 'Blue'), ('P', 'Purple'), ('Bwn', 'Brown'), ('Blk', 'Black')], default='W', max_length=5)),
                ('weight', models.CharField(choices=[('125', 'Less than 125'), ('135', '125 to Less than 135'), ('145', '135 to Less than 145'), ('155', '145 to Less than 155'), ('165', '155 to Less than 165'), ('175', '165 to Less than 175'), ('185', '175 to Less than 185'), ('195', '185 to Less than 195'), ('205', '195 to Less than 205'), ('215', '205 to Less than 215'), ('225', '215 to Less than 225'), ('235', '225 to Less than 235'), ('245', '235 to Less than 245'), ('H', '145 or More')], default='125', max_length=4)),
                ('points', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
        ),
        migrations.AddField(
            model_name='age',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sex'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(check=models.Q(('points__gte', 0), ('points__lte', 300)), name='Points value is valid between 1 and 300'),
        ),
    ]
