# Generated by Django 4.0.6 on 2022-07-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_age_rank_weight_tournament_sex_competitor_champions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date_of_tournament',
            field=models.DateTimeField(),
        ),
    ]
