# Generated by Django 4.0.6 on 2022-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_competitor_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
